name       : perl-alien-build-plugin-download-gitlab
version    : 0.01
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Build-Plugin-Download-GitLab-0.01.tar.gz : c1f089c8ea152a789909d48a83dbfcf2626f773daf30431c8622582b26aba902
homepage   : https://metacpan.org/dist/Alien-Build-Plugin-Download-GitLab
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Alien::Build plugin to download from GitLab
description: |
    Alien::Build plugin to download from GitLab 
rundeps    :
    - perl-alien-build
    - perl-path-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
